# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=false
org.gradle.configuration-cache=false

# Use the default mapping pipeline for Minecraft 26.3.
# Environment Properties
# You can find the latest versions here: https://projects.neoforged.net/neoforged/neoforge
# The Minecraft version must agree with the Neo version to get a valid artifact
minecraft_version=26.3
minecraft_version_range=[26.3,26.4)
neo_version=26.3.0.52-beta
neo_version_range=[26.3.0.0-beta,)

## Mod Properties
mod_id=beyonddimensions
mod_name=Beyond Dimensions
mod_license=MIT
mod_version=0.7.31
mod_group_id=com.wintercogs.beyonddimensions
mod_authors=Frostbite
mod_description=A mod provided some utilities.

## Mod Compat
jei_version=31.9.0.58
#curios_version=17.0.0-beta.2+26.3
ae_version=26.3.1-alpha
jade_version=26.3.5+neoforge
